name: Output Event Details
on:
  issues:
    types: [opened, closed]
jobs:
    output-job:
        runs-on: ubuntu-latest
        steps:
            - name: Display Github context object information
              run: echo "${{toJson(github.event)}}"