name: Output Event Details
on:
  issues:
    types: [opened]
jobs:
    output-job:
        runs-on: ubuntu-latest
        steps:
            - name: Display Events object information
              run: echo "${{toJson(github)}}"